[package]
name = "example-editor"
version = "0.7.1"
publish = false
edition.workspace = true

[dependencies]
gpui-kit = { workspace = true, features = ["tree-sitter-languages"] }
gpui-component-story = { path = "../../crates/story" }
autocorrect = "2.14.2"
chrono = "0.4"
color-lsp = "0.2.0"
lsp-types.workspace = true
serde_json.workspace = true
smol.workspace = true
tree-sitter-haskell = { package = "mesquite_haskell", git = "https://github.com/mesa-hills-research/mesquite", rev = "fef5b10845abe8fb435b2c4192aec3920d3f1898" }

[lints]
workspace = true
